### ISSUE TITLE
Crashes upon launch

### ISSUE THREAD

**Issue by DiamondHousefX** [god-jester/D3StudioFork#1]
![Screenshot 2022-01-04 185247](https://user-images.githubusercontent.com/62033316/148139526-38b0b7e4-9c09-4b4b-a7ce-7201fdd975ae.png)

Any ideas?

**Comment by god-jester** [comment]
Try the new v3.6.1! The fix is to "unblock" the DLLs in the bin folder, but I got rid of them in newest release. Reopen issue if it's not resolved!
